name: Checking
concurrency: 
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
env:
  GO_VERSION: 1.19

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
  check-proto-lint:
    name: Run proto lint
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.6.0


      - name: Fetching base branch
        run: |
          git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Running linter, checking breaking changes
        run: |
          buf lint

  check-generate:
    runs-on: ubuntu-latest
   
    needs:
      - check-proto-lint

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.6.0
      - name: generate proto
        run: make generate-proto
