name: Publish code generated
concurrency: 
  group: ci-workflow-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
env:
  GO_VERSION: 1.19

on:
  workflow_dispatch:
  push:
    branches:
      - master


jobs:
  check-proto-lint:
    name: Run proto lint
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.6.0


      - name: Fetching base branch
        run: |
          git fetch -u origin ${{ github.base_ref }}:${{ github.base_ref }}
      - name: Running linter, checking breaking changes
        run: |
          buf lint

  check-generate:
    runs-on: ubuntu-latest
   
    needs:
      - check-proto-lint
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.6.0
      - name: generate proto
        run: make generate-proto

  push-codegen:
    runs-on: ubuntu-latest
    needs:
      - check-generate
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1.6.0

      - name: generate proto
        run: make generate-proto

      - name: push to rpc-service repo
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
          RPC_SERVICE_REPO: rpc-service
        run: |
            git clone https://user:${{ env.GITHUB_TOKEN }}@github.com/linhbkhn95/${{ env.RPC_SERVICE_REPO }}
            cp -R pb/* ${{ env.RPC_SERVICE_REPO }}
            cd ${{ env.RPC_SERVICE_REPO }}
            echo "git status `git status`"
            
            if [[ -n $(git status --porcelain) ]]; then
              git config user.email "bot@github.com"  
              git config user.name "github-bot"
              git add .
              git commit -m "push code generated from rpc-proto"  
              git push

              date=`date "+%Y-%m-%d"`  
              short_hash=`git log --pretty=format:"%h" -1`  
              tag_name="$date-$short_hash"
              git tag $tag_name  
              git push origin $tag_name  
              git pull origin
            fi


